### ISSUE TITLE
Add test case for wxTreeListCtrl

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiTesting#25]
### Description:

The SDI tests need to include wxTreeCtrl, wxTreeListCtrl, and wxTreeListCtrl Column with coverage in all languages. Note that the wxPython code for these was incorrect -- see https://github.com/KeyWorksRW/wxUiEditor/issues/1516

Coverage.md lists ?? for both C++ and wxPython, and n/a for wxRuby3 -- so those should be updated after #1515 above and test case have been completed.

**Comment by Randalphwa** [comment]
I created a DataDlg dialog that covers:

- wxGrid
- wxPropertyGrid
- wxTreeCtrl
- wxTreeListCtrl
- wxDataView
- wxDataViewList
- wxDataViewTree

Besides creating and populating them, each container binds to at least one event, and displays that event in a list to verify that it is properly handled.

Note that wxRuby does not support any of the wxDataView containers.
